class DemoJsonData{
  static const racedata =
  """
  {
    "id": 50000,
    "name": "Island Rock",
    "peckingOrder": "A",
    "terrainId": 4,
    "distance": 200,
    "fee": 0.00075,
    "maxCapacity": 12,
    "currentCapacity": 12,
    "location": "Valletta, Malta",
    "minimumStartDelay": 3,
    "status": "finished",
    "startTime": 0,
    "prizePool": 0.0081,
    "paidStatus": "paid",
    "unlimitPO": 0,
    "startsAt": "2022-07-20T03:02:30.000Z",
    "endsAt": "2022-07-20T03:04:38.000Z",
    "payoutAttempts": 1,
    "type": "automatic",
    "group": 4,
    "feeUSD": 1.16,
    "prizePoolUSD": 12.53,
    "createdAt": "2022-07-20T01:47:30.000Z",
    "updatedAt": "2022-07-20T03:05:07.000Z",
    "terrain": {
        "name": "Rock",
        "image": "/terrain/rock_icon.png"
    },
    "lanes": [
        {
            "laneNumber": 1,
            "assignedAt": "2022-07-20T02:13:11.000Z",
            "chickenId": 12286,
            "userWalletId": "0x2b1410213554a5afd9fcd92f090f860aac1861c7",
            "userWallet": {
                "username": "Looney Tunes"
            },
            "chicken": {
                "id": 12286,
                "chknId": "chkn19436",
                "heritage": "Dorking",
                "perfection": 98,
                "stock": "Spicy",
                "talent": "Flight?",
                "image": "https://firebasestorage.googleapis.com/v0/b/chicken-derby.appspot.com/o/V2%2Fchkn19436.png?alt=media",
                "gender": "Rooster",
                "animal": "Chicken",
                "baseBody": "Bald Chicken",
                "stripes": null,
                "eyesType": "Bulging",
                "beakColor": "Gold",
                "beakAccessory": null,
                "combColor": "Orange",
                "wattleColor": "Orange",
                "legs": "legsRooster",
                "background": "Amethyst",
                "races": 553,
                "firsts": 49,
                "seconds": 44,
                "thirds": 52,
                "earnings": 836.68,
                "situation": "Barn",
                "poPoints": 71,
                "hair": null,
                "necklace": null,
                "glasses": null,
                "jacket": null,
                "shoes": null,
                "fatherID": null,
                "motherID": null,
                "name": "Theater of the Mind",
                "chickRaces": 7,
                "createdAt": "2022-07-27T14:30:06.000Z",
                "updatedAt": "2022-07-31T08:09:10.000Z",
                "position": 11,
                "owner": "Looney Tunes",
                "cumulativeSegmentSize": 114.74366029567368
            }
        },
        {
            "laneNumber": 2,
            "assignedAt": "2022-07-20T02:09:38.000Z",
            "chickenId": 16036,
            "userWalletId": "0xab76c8a0a8fb2fb2b4a9a7f0df541173ca6504bb",
            "userWallet": {
                "username": "Bazaar Imaginarium"
            },
            "chicken": {
                "id": 16036,
                "chknId": "chkn340",
                "heritage": "Serama",
                "perfection": 96,
                "stock": "Spicy",
                "talent": "Flight?",
                "image": "https://firebasestorage.googleapis.com/v0/b/chicken-derby.appspot.com/o/V2%2Fchkn340.png?alt=media",
                "gender": "Rooster",
                "animal": "Chicken",
                "baseBody": "Shocking Pink",
                "stripes": null,
                "eyesType": "Crosseyed",
                "beakColor": "Gold",
                "beakAccessory": null,
                "combColor": "Black",
                "wattleColor": "Black",
                "legs": "legsRooster",
                "background": "Spring",
                "races": 203,
                "firsts": 9,
                "seconds": 16,
                "thirds": 11,
                "earnings": 105,
                "situation": "Barn",
                "poPoints": 89,
                "hair": null,
                "necklace": null,
                "glasses": null,
                "jacket": null,
                "shoes": null,
                "fatherID": null,
                "motherID": null,
                "name": "Ted Svertesky",
                "chickRaces": 7,
                "createdAt": "2022-07-27T14:30:06.000Z",
                "updatedAt": "2022-07-28T18:22:10.000Z",
                "position": 5,
                "owner": "Bazaar Imaginarium",
                "cumulativeSegmentSize": 113.1973214539598
            }
        },
        {
            "laneNumber": 3,
            "assignedAt": "2022-07-20T03:00:29.000Z",
            "chickenId": 4453,
            "userWalletId": "0x09de3bfad2fe056bb35f4c1e2ffeb17cfeeea3c5",
            "userWallet": {
                "username": "Yeh the boys 🔤"
            },
            "chicken": {
                "id": 4453,
                "chknId": "chkn7774",
                "heritage": "Lakenvelder",
                "perfection": 99,
                "stock": "Spicy",
                "talent": "Chickenapult",
                "image": "https://firebasestorage.googleapis.com/v0/b/chicken-derby.appspot.com/o/V2%2Fchkn7774.png?alt=media",
                "gender": "Rooster",
                "animal": "Chicken",
                "baseBody": "Wild Moss",
                "stripes": null,
                "eyesType": "Sleepy",
                "beakColor": "Yellow",
                "beakAccessory": null,
                "combColor": "White",
                "wattleColor": "White",
                "legs": "legsRooster",
                "background": "Amethyst",
                "races": 325,
                "firsts": 52,
                "seconds": 28,
                "thirds": 17,
                "earnings": 704.19,
                "situation": "Barn",
                "poPoints": 79,
                "hair": null,
                "necklace": null,
                "glasses": null,
                "jacket": null,
                "shoes": null,
                "fatherID": null,
                "motherID": null,
                "name": "Smooth Operator",
                "chickRaces": 7,
                "createdAt": "2022-07-27T14:30:05.000Z",
                "updatedAt": "2022-07-28T19:04:40.000Z",
                "position": 8,
                "owner": "Yeh the boys 🔤",
                "cumulativeSegmentSize": 114.27718942370116
            }
        },
        {
            "laneNumber": 4,
            "assignedAt": "2022-07-20T02:46:37.000Z",
            "chickenId": 16322,
            "userWalletId": "0x9050dabf5903561d07148460a38fa4a3d39b2c9f",
            "userWallet": {
                "username": "Red Star Belgrade"
            },
            "chicken": {
                "id": 16322,
                "chknId": "chkn8482",
                "heritage": "Lakenvelder",
                "perfection": 97,
                "stock": "Spicy",
                "talent": "Moving Walkway",
                "image": "https://firebasestorage.googleapis.com/v0/b/chicken-derby.appspot.com/o/V2%2Fchkn8482.png?alt=media",
                "gender": "Rooster",
                "animal": "Chicken",
                "baseBody": "Screamin Green",
                "stripes": null,
                "eyesType": "Shocked",
                "beakColor": "White",
                "beakAccessory": null,
                "combColor": "Red",
                "wattleColor": "Red",
                "legs": "legsRooster",
                "background": "Autumn",
                "races": 358,
                "firsts": 41,
                "seconds": 27,
                "thirds": 23,
                "earnings": 239.18,
                "situation": "Racing Pen",
                "poPoints": 61,
                "hair": null,
                "necklace": null,
                "glasses": null,
                "jacket": null,
                "shoes": null,
                "fatherID": null,
                "motherID": null,
                "name": null,
                "chickRaces": 7,
                "createdAt": "2022-07-27T14:30:06.000Z",
                "updatedAt": "2022-07-31T13:09:04.000Z",
                "position": 12,
                "owner": "Red Star Belgrade",
                "cumulativeSegmentSize": 115.0105935375778
            }
        },
        {
            "laneNumber": 5,
            "assignedAt": "2022-07-20T02:53:05.000Z",
            "chickenId": 32945,
            "userWalletId": "0xe1474922e5dba2c0947192713c05d4e4540bad9f",
            "userWallet": {
                "username": "HemsworthFarm Racing"
            },
            "chicken": {
                "id": 32945,
                "chknId": "chkn7866",
                "heritage": "Lakenvelder",
                "perfection": 99,
                "stock": "Spicy",
                "talent": "Anvil",
                "image": "https://firebasestorage.googleapis.com/v0/b/chicken-derby.appspot.com/o/V2%2Fchkn7866.png?alt=media",
                "gender": "Rooster",
                "animal": "Chicken",
                "baseBody": "Screamin Green",
                "stripes": null,
                "eyesType": "Shocked",
                "beakColor": "White",
                "beakAccessory": null,
                "combColor": "Pink",
                "wattleColor": "Pink",
                "legs": "legsRooster",
                "background": "Amethyst",
                "races": 374,
                "firsts": 69,
                "seconds": 26,
                "thirds": 26,
                "earnings": 1196.46,
                "situation": "Barn",
                "poPoints": 77,
                "hair": null,
                "necklace": null,
                "glasses": null,
                "jacket": null,
                "shoes": null,
                "fatherID": null,
                "motherID": null,
                "name": "Kraken",
                "chickRaces": 7,
                "createdAt": "2022-07-27T14:30:07.000Z",
                "updatedAt": "2022-07-27T14:30:07.000Z",
                "position": 1,
                "owner": "HemsworthFarm Racing",
                "raceEarnings": 6.89,
                "cumulativeSegmentSize": 112.2000977045745
            }
        },
        {
            "laneNumber": 6,
            "assignedAt": "2022-07-20T02:00:26.000Z",
            "chickenId": 2321,
            "userWalletId": "0xbca8c43054ca7e74abe3bde6671338c283c1e377",
            "userWallet": {
                "username": "Speaker City Racing"
            },
            "chicken": {
                "id": 2321,
                "chknId": "chkn8210",
                "heritage": "Lakenvelder",
                "perfection": 98,
                "stock": "Spicy",
                "talent": "Chickenapult",
                "image": "https://firebasestorage.googleapis.com/v0/b/chicken-derby.appspot.com/o/V2%2Fchkn8210.png?alt=media",
                "gender": "Rooster",
                "animal": "Chicken",
                "baseBody": "Manic Mint",
                "stripes": null,
                "eyesType": "Sleepy",
                "beakColor": "White",
                "beakAccessory": null,
                "combColor": "Green",
                "wattleColor": "Green",
                "legs": "legsRooster",
                "background": "Autumn",
                "races": 359,
                "firsts": 46,
                "seconds": 29,
                "thirds": 21,
                "earnings": 548.59,
                "situation": "Barn",
                "poPoints": 61,
                "hair": null,
                "necklace": null,
                "glasses": null,
                "jacket": null,
                "shoes": null,
                "fatherID": null,
                "motherID": null,
                "name": "Donatello",
                "chickRaces": 7,
                "createdAt": "2022-07-27T14:30:06.000Z",
                "updatedAt": "2022-07-31T05:22:40.000Z",
                "position": 6,
                "owner": "Speaker City Racing",
                "cumulativeSegmentSize": 113.45716702064992
            }
        },
        {
            "laneNumber": 7,
            "assignedAt": "2022-07-20T02:31:05.000Z",
            "chickenId": 17049,
            "userWalletId": "0x8c85b352748d40dc94f6ef484796d4eceb2713b5",
            "userWallet": {
                "username": "Top Coop"
            },
            "chicken": {
                "id": 17049,
                "chknId": "chkn18580",
                "heritage": "Dorking",
                "perfection": 100,
                "stock": "Spicy",
                "talent": "Coober",
                "image": "https://firebasestorage.googleapis.com/v0/b/chicken-derby.appspot.com/o/V2%2Fchkn18580.png?alt=media",
                "gender": "Rooster",
                "animal": "Chicken",
                "baseBody": "Orange Will",
                "stripes": null,
                "eyesType": "Sleepy",
                "beakColor": "Yellow",
                "beakAccessory": null,
                "combColor": "Pink",
                "wattleColor": "Pink",
                "legs": "legsRooster",
                "background": "Spring",
                "races": 342,
                "firsts": 19,
                "seconds": 28,
                "thirds": 31,
                "earnings": 330.53,
                "situation": "Barn",
                "poPoints": 85,
                "hair": null,
                "necklace": null,
                "glasses": null,
                "jacket": null,
                "shoes": null,
                "fatherID": null,
                "motherID": null,
                "name": null,
                "chickRaces": 7,
                "createdAt": "2022-07-27T14:30:05.000Z",
                "updatedAt": "2022-07-29T07:37:30.000Z",
                "position": 9,
                "owner": "Top Coop",
                "cumulativeSegmentSize": 114.41958526207593
            }
        },
        {
            "laneNumber": 8,
            "assignedAt": "2022-07-20T02:59:26.000Z",
            "chickenId": 30824,
            "userWalletId": "0x9938e0be7c80b533d08d41ff02d7399e0e5facb5",
            "userWallet": {
                "username": "Dude Wheres My Coop"
            },
            "chicken": {
                "id": 30824,
                "chknId": "chkn3141",
                "heritage": "Sultan",
                "perfection": 95,
                "stock": "Spicy",
                "talent": "Jetpack",
                "image": "https://firebasestorage.googleapis.com/v0/b/chicken-derby.appspot.com/o/V2%2Fchkn3141.png?alt=media",
                "gender": "Hen",
                "animal": "Chicken",
                "baseBody": "Sapphire",
                "stripes": null,
                "eyesType": "Cockeyed",
                "beakColor": "Orange",
                "beakAccessory": null,
                "combColor": "Pink",
                "wattleColor": "Pink",
                "legs": "legsHen",
                "background": "Autumn",
                "races": 189,
                "firsts": 6,
                "seconds": 17,
                "thirds": 7,
                "earnings": 54.43,
                "situation": "Barn",
                "poPoints": 78,
                "hair": null,
                "necklace": null,
                "glasses": null,
                "jacket": null,
                "shoes": null,
                "fatherID": null,
                "motherID": null,
                "name": "Dwight K Schrute",
                "chickRaces": 7,
                "createdAt": "2022-07-27T14:30:07.000Z",
                "updatedAt": "2022-07-30T01:46:10.000Z",
                "position": 4,
                "owner": "Dude Wheres My Coop",
                "cumulativeSegmentSize": 112.9176898014777
            }
        },
        {
            "laneNumber": 9,
            "assignedAt": "2022-07-20T02:23:55.000Z",
            "chickenId": 26622,
            "userWalletId": "0x25b335f53e3e09d854a125c36fb9bc722c743ff0",
            "userWallet": {
                "username": "The Bok Bok Boks D³ 🔤"
            },
            "chicken": {
                "id": 26622,
                "chknId": "chkn7858",
                "heritage": "Lakenvelder",
                "perfection": 99,
                "stock": "Spicy",
                "talent": "Growth",
                "image": "https://firebasestorage.googleapis.com/v0/b/chicken-derby.appspot.com/o/V2%2Fchkn7858.png?alt=media",
                "gender": "Rooster",
                "animal": "Chicken",
                "baseBody": "Screamin Green",
                "stripes": null,
                "eyesType": "Shocked",
                "beakColor": "Gold",
                "beakAccessory": null,
                "combColor": "Blue",
                "wattleColor": "Blue",
                "legs": "legsRooster",
                "background": "Spring",
                "races": 546,
                "firsts": 90,
                "seconds": 44,
                "thirds": 43,
                "earnings": 525.12,
                "situation": "Barn",
                "poPoints": 76,
                "hair": null,
                "necklace": null,
                "glasses": null,
                "jacket": null,
                "shoes": null,
                "fatherID": null,
                "motherID": null,
                "name": "Reptar 🦖",
                "chickRaces": 7,
                "createdAt": "2022-07-27T14:30:06.000Z",
                "updatedAt": "2022-07-29T20:56:30.000Z",
                "position": 10,
                "owner": "The Bok Bok Boks D³ 🔤",
                "cumulativeSegmentSize": 114.57004399959696
            }
        },
        {
            "laneNumber": 10,
            "assignedAt": "2022-07-20T01:53:05.000Z",
            "chickenId": 15504,
            "userWalletId": "0x25b335f53e3e09d854a125c36fb9bc722c743ff0",
            "userWallet": {
                "username": "The Bok Bok Boks D³ 🔤"
            },
            "chicken": {
                "id": 15504,
                "chknId": "chkn999",
                "heritage": "Serama",
                "perfection": 93,
                "stock": "Spicy",
                "talent": "Devolution",
                "image": "https://firebasestorage.googleapis.com/v0/b/chicken-derby.appspot.com/o/V2%2Fchkn999.png?alt=media",
                "gender": "Hen",
                "animal": "Chicken",
                "baseBody": "Merah Red",
                "stripes": null,
                "eyesType": "Determined",
                "beakColor": "Gold",
                "beakAccessory": null,
                "combColor": "Green",
                "wattleColor": "Green",
                "legs": "legsHen",
                "background": "Amethyst",
                "races": 313,
                "firsts": 25,
                "seconds": 30,
                "thirds": 21,
                "earnings": 190.81,
                "situation": "Barn",
                "poPoints": 85,
                "hair": null,
                "necklace": null,
                "glasses": null,
                "jacket": null,
                "shoes": null,
                "fatherID": null,
                "motherID": null,
                "name": "Red Power Ranger",
                "chickRaces": 7,
                "createdAt": "2022-07-27T14:30:06.000Z",
                "updatedAt": "2022-07-29T07:37:30.000Z",
                "position": 3,
                "owner": "The Bok Bok Boks D³ 🔤",
                "raceEarnings": 1.88,
                "cumulativeSegmentSize": 112.52439235513526
            }
        },
        {
            "laneNumber": 11,
            "assignedAt": "2022-07-20T01:49:08.000Z",
            "chickenId": 28845,
            "userWalletId": "0xd4b0641bd1ca3ebb725053460312c3aa97355866",
            "userWallet": {
                "username": "Better Blake Racing"
            },
            "chicken": {
                "id": 28845,
                "chknId": "chkn671",
                "heritage": "Serama",
                "perfection": 94,
                "stock": "Spicy",
                "talent": "Dig",
                "image": "https://firebasestorage.googleapis.com/v0/b/chicken-derby.appspot.com/o/V2%2Fchkn671.png?alt=media",
                "gender": "Hen",
                "animal": "Chicken",
                "baseBody": "Classic",
                "stripes": null,
                "eyesType": "Crosseyed",
                "beakColor": "Orange",
                "beakAccessory": null,
                "combColor": "Green",
                "wattleColor": "Green",
                "legs": "legsHen",
                "background": "Autumn",
                "races": 414,
                "firsts": 18,
                "seconds": 16,
                "thirds": 35,
                "earnings": 158.17,
                "situation": "Barn",
                "poPoints": 81,
                "hair": null,
                "necklace": null,
                "glasses": null,
                "jacket": null,
                "shoes": null,
                "fatherID": null,
                "motherID": null,
                "name": "Kirk Jones",
                "chickRaces": 7,
                "createdAt": "2022-07-27T14:30:06.000Z",
                "updatedAt": "2022-07-31T10:27:00.000Z",
                "position": 7,
                "owner": "Better Blake Racing",
                "cumulativeSegmentSize": 113.7411727885014
            }
        },
        {
            "laneNumber": 12,
            "assignedAt": "2022-07-20T02:59:00.000Z",
            "chickenId": 3475,
            "userWalletId": "0x9938e0be7c80b533d08d41ff02d7399e0e5facb5",
            "userWallet": {
                "username": "Dude Wheres My Coop"
            },
            "chicken": {
                "id": 3475,
                "chknId": "chkn2861",
                "heritage": "Sultan",
                "perfection": 96,
                "stock": "Spicy",
                "talent": "Blue Rooster",
                "image": "https://firebasestorage.googleapis.com/v0/b/chicken-derby.appspot.com/o/V2%2Fchkn2861.png?alt=media",
                "gender": "Hen",
                "animal": "Chicken",
                "baseBody": "Purple Wine",
                "stripes": null,
                "eyesType": "Angry",
                "beakColor": "Orange",
                "beakAccessory": null,
                "combColor": "White",
                "wattleColor": "White",
                "legs": "legsHen",
                "background": "Spring",
                "races": 35,
                "firsts": 3,
                "seconds": 4,
                "thirds": 4,
                "earnings": 11.49,
                "situation": "Barn",
                "poPoints": 69,
                "hair": null,
                "necklace": null,
                "glasses": null,
                "jacket": null,
                "shoes": null,
                "fatherID": null,
                "motherID": null,
                "name": "Bellatrix Lestrange",
                "chickRaces": 7,
                "createdAt": "2022-07-27T14:30:07.000Z",
                "updatedAt": "2022-07-30T02:30:10.000Z",
                "position": 2,
                "owner": "Dude Wheres My Coop",
                "raceEarnings": 3.76,
                "cumulativeSegmentSize": 112.33943095312095
            }
        }
    ]
}
  """;
}